import turtle as t
t.pensize(15)

t.penup()
t.goto(0,200)
t.pendown()


t.left(180)
t.forward(50)
t.circle(75,180)
t.forward(00)
t.circle(-75,180)
t.forward(50)
t.penup()
t.goto(0,0)
t.left(180)
t.pendown()
t.hideturtle()


import turtle as t
t.pensize(15)

t.penup()
t.goto(0,-300)
t.pendown()

t.left(90)
t.right(20)
t.forward(200)
t.right(140)
t.forward(200)
t.backward(100)
t.right(110)
t.forward(60)
